name: my first workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello World"
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: say good bye
        run: echo "Good bye"
